# этап production (production-stage)
FROM nginx:stable-alpine

COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./dist /usr/share/nginx/html
COPY ./robots.txt /usr/share/nginx/html
COPY ./sitemap.xml /usr/share/nginx/html
COPY ./maintaince.html /usr/share/nginx/html/50x.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
